version: "3.8"

services:
 postgres:
  container_name: postgres-2
  image: postgres:13.0-alpine
  ports:
   - 5433:5432
  networks:
   - java_network
  environment:
   - POSTGRES_PASSWORD=postgres234
 mongo:
  container_name: mongo-1
  image: mongo:4-xenial
  ports:
   - 27017:27017
  networks:
   - java_network
 redis:
  container_name: redis-1
  image: redis:5
  ports:
   - 6379:6379
  networks:
   - java_network
 demo-hello-world:
  container_name: demo-1
  image: demo-hello-world:1.1
  ports:
   - 8080:8080
  depends_on:
   - postgres
   - mongo
   - redis
  environment:
   - NAME=GAW
   - POSTGRES_HOST=postgres-2
   - POSTGRES_PORT=5432
   - MONGO_HOST=mongo-1
   - MONGO_PORT=27017
   - REDIS_HOST=redis-1
   - REDIS_PORT=6379
  networks:
   - java_network
networks:
 java_network:
  name: java_network